### ISSUE TITLE
SSR support for useResizeObserver

### ISSUE THREAD

**Issue by thelevicole** [jaredLunde/react-hook#314]
**Describe the bug**
Using the `useResizeObserver` hook in a NextJS will throw "Error: window is not defined" at build time.

**Expected behavior**
Obviously the resize observer can't run server side so I'd expect it to silently fail/not call the callback.

**Additional context**
`if (typeof window === 'undefined') return;` might do ¯\\\_(ツ)_/¯

**Comment by jaredLunde** [comment]
You can add a polyfill on the server to get around this

**Comment by thelevicole** [comment]
@jaredLunde good idea, I achieved this with:

```ts
import useResizeObserver, { UseResizeObserverCallback } from '@react-hook/resize-observer'

class ServerSideResizeObserverPolyfill {
  constructor(callback: ResizeObserverCallback) {}
  observe(target: Element, options?: ResizeObserverOptions) {}
  unobserve(target: Element) {}
}

export default function useResizeObserverSsr<T extends Element>(
  target: React.RefObject<T> | React.ForwardedRef<T> | T | null,
  callback: UseResizeObserverCallback,
) {
  return useResizeObserver(target, callback, {
    polyfill: typeof window === 'undefined' ? ServerSideResizeObserverPolyfill : null,
  })
}
```

**Comment by thelevicole** [comment]
Closing

**Comment by jonrajavuori-academia** [comment]
SSR is only becoming more and more common, and while it might be "obvious" that ResizeObserver is only available client-side, it would be appropriate and convenient for a React hook that wraps it to cleanly handle SSR without blowing up, so that components using the hook can be included in SSR component trees without any issue. This is becoming a best practice in general across the board. https://github.com/ZeeCoder/use-resize-observer does so, for instance - but it has a less powerful interface, not providing the actual entries, so we'd prefer to use this library.

Would it not be simple to just build in the behavior of @thelevicole 's snippet when window is undefined?
